apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.x.x
    
    helm:
      values: |
        # 1. Node Exporter 포트 변경 (9101)
        nodeExporter:
          enabled: true
          service:
            port: 9101
            targetPort: 9101
          extraArgs:
            - --web.listen-address=:9101

        # 2. [핵심] K8s 내부 Grafana 비활성화 (Centre Grafana 사용)
        grafana:
          enabled: false
          # 비활성화했으므로 비밀번호나 NodePort 설정 불필요

        # 3. Prometheus 설정 (데이터 원본 노출)
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi
            # Centre 서버가 데이터를 가져갈 수 있도록 구멍 뚫기
            service:
              type: NodePort
              nodePort: 30090