# argoCD 기반으로 구축하기 위한 그룹 / appi 버전
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  finalizers: 
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  source:
    repoURL: https://github.com/Paul2021-R/project-protostar-k8s-config.git
    targetRevision: main
    path: infrastructure/rabbitmq

  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true