apiVersion: v1
kind: ConfigMap
metadata:
  name: protostar-postgres-init
  namespace: service
  labels:
    app: protostar
    tier: postgres
data:
  init.sql: |
    CREATE EXTENSION IF NOT EXISTS vector;