apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: jenkins
  repo: https://charts.jenkins.io
  version: 5.4.3 # (이 차트 버전이 Jenkins LTS 최신 버전을 설치해줍니다)
  releaseName: jenkins
  namespace: jenkins
  valuesFile: values.yaml