apiVersion: "acid.zalan.do/v1"
kind: "postgresql"
metadata:
  name: "protostar-db" # 클러스터 이름 (내부 서비스 이름: protostar-db.default.svc.cluster.local)
  namespace: default
spec:
  # 1 고가용성 및 복제(HA)
  teamId: "protostar"
  volume:
    size: "10Gi" # 무거운 파일은 MinIO 사용 예정, 따라서 유저 데이터를 위하여 적절하게 설정 
  numberOfInstances: 3

  # 2 DB 사용자 및 데이터 베이스 설정
  users:
    protostar_user: # Demo 개발 용이므로 우선 진행을 위하여 최대 권한으로 시작
      - superuser # 이렇게 설정시 비밀번호 자동 생성, 난수화하여 k8s secret에 저장됨
  databases:
    protostar_db: protostar_user

  # 3 Docker 이미지 버전
  dockerImage: registry.opensource.zalan.do/acid/spilo-pg16:3.0-p1
  postgresql:
    version: "16"

  # 4 RAG를 위한 pgvector 확장 활성화
  initdb:
    - scripts:
      - CREATE EXTENSION IF NOT EXISTS vector;

  # 5 연결 풀링 활성화(MSA 환경 최적화)
  enableConnectionPooler: true # PgBouncer 자동 배포 및 관리 활성화
  # 기본적으로 PostgreSQL 은 연결 당 프로세스 1개로 설정됨 
  # MSA 설정시 그대로 연결하는 순간 자원 사용량 터질 수 있음
  # 해당 설저 켜줘야 소수의 연결만 설정하여 자원 사용량 최적의 로드벨런싱 진행해줌
