apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - external-services.yaml
  - gateway.yaml
  - httproutes.yaml
  - certificates.yaml
  - nginxproxy.yaml
  - jenkins-statefulset.yaml
  - jenkins-service.yaml