# prod/infra/nginxproxy.yaml
apiVersion: gateway.nginx.org/v1alpha2
kind: NginxProxy
metadata:
  name: infra-ngf-proxy-config
  namespace: infra-gateway
spec:
  rewriteClientIP:
    mode: ProxyProtocol
    trustedAddresses:
      - type: CIDR
        value: 0.0.0.0/0
  kubernetes:
    service:
      loadBalancerIP: "192.168.0.41"  # Centre IP, svclb를 Centre 노드에만 고정