apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # 인프라 공통
  - ../../infrastructure/cert-manager-config
  
  # 1. Grafana
  - ../../infrastructure/monitoring/grafana
  # 2. Jenkins
  - ../../infrastructure/jenkins
  # 3. ArgoCD [추가됨]
  - ../../infrastructure/argocd
  
  # Ingress 설정들
  - ingress-grafana.yaml
  - ingress-jenkins.yaml
  - ingress-argocd.yaml