apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - httproutes.yaml
  - certificates.yaml
  - nginxproxy.yaml
  - redis-statefulset.yaml
  - redis-headless-service.yaml
  - secret.yaml