apiVersion: gateway.nginx.org/v1alpha2
kind: NginxProxy
metadata:
  name: service-ngf-proxy-config
  namespace: service-gateway
spec:
  kubernetes:
    deployment:
      pod:
        nodeSelector:
          kubernetes.io/hostname: hansol-a5
    service:
      loadBalancerIP: "192.168.0.37"